version : "3.7"
services: 
  db:
    image : postgres
    environment: 
          POSTGRES_PASSWORD: test 
          POSTGRES_USER: postgres 
          POSTGRES_DB: food-testing-app
    ports :
      - "5433:5432"